- BASE:
    EXP: 'deep_traj'
- MODEL:
    - :
      HIDDEN_DIM: 2048
    - subnode4:
      GRU_LEN : 120
- DATA :
    - DATALOADER:
      PROB: 0.5 # random horizontal flip
      RE_PROB: 0.5 # random erasing
      PADDING: 10
      PIXEL_MEAN: [ 0.5, 0.5, 0.5 ]
      PIXEL_STD: [ 0.5, 0.5, 0.5 ]
    - DATASET:
      NAMES: ('DukeMTMC','MOT16')
      ROOT_DIR: ('/media/syh/ssd2/data/deep_traj')
- TRAIN :
    - subnode3:
      MAX_EPOCHS: 120
      BASE_LR: 0.008
    - subnode4:
      key7: value7
      key8: value8
- TEST :
    EVAL: True
    IMS_PER_BATCH: value6
    WEIGHT: value7
    OUTPUT_DIR: '/media/syh/hdd/checkpoints/deep_traj'